In [4]:
#Dependencies
import pandas as pd
from sqlalchemy import create_engine
from bs4 import BeautifulSoup
from splinter import Browser
from splinter.exceptions import ElementDoesNotExist
import pandas as pd
import requests
import os

In [7]:
csv_file = "../Resources/player_data.csv"
player_data_df = pd.read_csv("player_data.csv")
player_data_df.head()

,name,year_start,year_end,position,height,weight,birth_date,college
0,Alaa Abdelnaby,1991,1995,F-C,6-10,240.0,"June 24, 1968",Duke University
1,Zaid Abdul-Aziz,1969,1978,C-F,6-9,235.0,"April 7, 1946",Iowa State University
2,Kareem Abdul-Jabbar,1970,1989,C,7-2,225.0,"April 16, 1947","University of California, Los Angeles"
3,Mahmoud Abdul-Rauf,1991,2001,G,6-1,162.0,"March 9, 1969",Louisiana State University
4,Tariq Abdul-Wahad,1998,2003,F,6-6,223.0,"November 3, 1974",San Jose State University

In [15]:
player_data_df = player_data_df[['name', 'year_start', 'year_end', 'position','birth_date'] ]
player_data_df

                     name  year_start  year_end position         birth_date
0          Alaa Abdelnaby        1991      1995      F-C      June 24, 1968
1         Zaid Abdul-Aziz        1969      1978      C-F      April 7, 1946
2     Kareem Abdul-Jabbar        1970      1989        C     April 16, 1947
3      Mahmoud Abdul-Rauf        1991      2001        G      March 9, 1969
4       Tariq Abdul-Wahad        1998      2003        F   November 3, 1974
5     Shareef Abdur-Rahim        1997      2008        F  December 11, 1976
6           Tom Abernethy        1977      1981        F        May 6, 1954
7             Forest Able        1957      1957        G      July 27, 1932
8          John Abramovic        1947      1948        F   February 9, 1919
9            Alex Abrines        2017      2018      G-F     August 1, 1993
10             Alex Acker        2006      2009        G   January 21, 1983
11           Don Ackerman        1954      1954        G  September 4, 1930
12             Mark Acres        1988      1993      F-C  November 15, 1962
13              Bud Acton        1968      1968        F   January 11, 1942
14             Quincy Acy        2013      2018        F    October 6, 1990
15            Alvan Adams        1976      1988      C-F      July 19, 1954
16              Don Adams        1971      1977        F  November 27, 1947
17           George Adams        1973      1975      F-G       May 15, 1949
18           Hassan Adams        2007      2009        G      June 20, 1984
19           Jordan Adams        2015      2016        G       July 8, 1994
20          Michael Adams        1986      1996        G   January 19, 1963
21           Steven Adams        2014      2018        C      July 20, 1993
22         Rafael Addison        1987      1997      F-G      July 22, 1964
23            Bam Adebayo        2018      2018      C-F      July 18, 1997
24           Rick Adelman        1969      1975        G      June 16, 1946
25            Jeff Adrien        2011      2015        F  February 10, 1986
26          Arron Afflalo        2008      2018        G   October 15, 1985
27           Maurice Ager        2007      2011        G   February 9, 1984
28           Mark Aguirre        1982      1994      F-G  December 10, 1959
29           Blake Ahearn        2008      2012        G       May 27, 1984
...                   ...         ...       ...      ...                ...
4520          James Young        2015      2017      G-F    August 16, 1995
4521            Joe Young        2016      2018        G      June 27, 1992
4522       Korleone Young        1999      1999        F  December 31, 1978
4523        Michael Young        1985      1990      F-G    January 2, 1961
4524           Nick Young        2008      2018      G-F       June 1, 1985
4525          Perry Young        1987      1987        G     August 4, 1963
4526            Sam Young        2010      2013        F       June 1, 1985
4527       Thaddeus Young        2008      2018        F      June 21, 1988
4528            Tim Young        2000      2000        C   February 6, 1976
4529              Sun Yue        2009      2009        G   November 6, 1985
4530        Max Zaslofsky        1947      1956      G-F   December 7, 1925
4531         Zeke Zawoluk        1953      1955      F-C   October 13, 1930
4532          Cody Zeller        2014      2018      C-F    October 5, 1992
4533          Dave Zeller        1962      1962        G       June 8, 1939
4534          Gary Zeller        1971      1972        G  November 20, 1947
4535         Harry Zeller        1947      1947      C-F      July 10, 1919
4536          Luke Zeller        2013      2013        C      April 7, 1987
4537         Tyler Zeller        2013      2018      F-C   January 17, 1990
4538            Tony Zeno        1980      1980        F    October 1, 1957
4539     Phil Zevenbergen        1988      1988        C     April 13, 1964
4540          Wang Zhizhi        2001      2005        C       July 8, 1977
4541         George Zidek        1996      1998        C     August 2, 1973
4542    Derrick Zimmerman        2006      2006        G   December 2, 1981
4543    Stephen Zimmerman        2017      2017        C  September 9, 1996
4544          Paul Zipser        2017      2018      G-F  February 18, 1994
4545           Ante Zizic        2018      2018      F-C    January 4, 1997
4546             Jim Zoet        1983      1983        C  December 20, 1953
4547            Bill Zopf        1971      1971        G       June 7, 1948
4548          Ivica Zubac        2017      2018        C     March 18, 1997
4549           Matt Zunic        1949      1949      G-F  December 19, 1919

[4550 rows x 5 columns]

In [ ]:
#player_data_df.rename(columns = {})

In [21]:

dt = datetime.datetime.strptime('%m-%d-%y')

birth_date = 'birth_date'.format(dt.year, dt.month, dt.day % 100)

NameError: name 'datetime' is not defined